package devPilot.backend.services;

import java.util.regex.Pattern;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

/**
 * ContentGovernanceService — Pillar 1: Guardrails, Privacy & Content Governance.
 *
 * Runs BEFORE any content touches the vector store:
 *  1. Secret / PII redaction  — masks API keys, tokens, passwords, emails, IPs
 *  2. Generated-file detection — flags files that should be skipped entirely
 *  3. License-header stripping — removes boilerplate copyright blocks from file tops
 */
@Service
public class ContentGovernanceService {

    private static final Logger log = LoggerFactory.getLogger(ContentGovernanceService.class);

    // ── Secret / PII Patterns ───────────────────────────────────────────────────

    /** Generic high-entropy token patterns: Bearer …, sk-…, ghp_…, AKIA…, xox…  */
    private static final Pattern BEARER_TOKEN =
            Pattern.compile("(?i)(Bearer\\s+)[A-Za-z0-9\\-._~+/]{20,}", Pattern.CASE_INSENSITIVE);

    private static final Pattern GENERIC_SECRET_KEY =
            Pattern.compile("(?i)\\b(sk-|ghp_|gho_|ghs_|github_pat_|AKIA|xoxb-|xoxp-)[A-Za-z0-9\\-_]{10,}");

    /** .env-style assignments: PASSWORD=abc123, SECRET=…, TOKEN=…, KEY=…, APIKEY=…  */
    private static final Pattern ENV_ASSIGNMENT =
            Pattern.compile("(?i)\\b(password|passwd|secret|token|api[_-]?key|private[_-]?key|auth[_-]?key|access[_-]?key|client[_-]?secret)\\s*[=:]\\s*[\"']?([^\\s\"'\\n]{6,})[\"']?");

    /** PEM private key blocks */
    private static final Pattern PEM_PRIVATE_KEY =
            Pattern.compile("-----BEGIN (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----[\\s\\S]*?-----END (RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----");

    /** Email addresses */
    private static final Pattern EMAIL =
            Pattern.compile("[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}");

    /** IPv4 addresses that look like internal/private infrastructure IPs */
    private static final Pattern PRIVATE_IP =
            Pattern.compile("\\b(10\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|172\\.(1[6-9]|2\\d|3[01])\\.\\d{1,3}\\.\\d{1,3}|192\\.168\\.\\d{1,3}\\.\\d{1,3})\\b");

    /** Connection strings with embedded credentials */
    private static final Pattern CONNECTION_STRING =
            Pattern.compile("(?i)(mongodb|postgres|mysql|redis|amqp)://[^:@\\s]+:[^@\\s]+@");

    // ── Generated-File Markers ──────────────────────────────────────────────────

    /** File names that are always auto-generated and should never be indexed */
    private static final java.util.Set<String> GENERATED_FILE_NAMES = java.util.Set.of(
            "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "gemfile.lock",
            "poetry.lock", "composer.lock", "cargo.lock", "pipfile.lock",
            "gradle.lockfile", ".DS_Store"
    );

    /** File name suffixes that indicate generated/minified output */
    private static final java.util.Set<String> GENERATED_SUFFIXES = java.util.Set.of(
            ".min.js", ".min.css", ".bundle.js", ".chunk.js",
            ".map", ".snap"   // source maps and test snapshots
    );

    /** Content markers that appear in auto-generated file headers */
    private static final java.util.Set<String> GENERATED_CONTENT_MARKERS = java.util.Set.of(
            "@generated", "DO NOT EDIT", "DO NOT MODIFY", "AUTO-GENERATED",
            "AUTOGENERATED", "Code generated by", "This file is auto-generated",
            "This file was automatically generated"
    );

    // ── License Header Patterns ─────────────────────────────────────────────────

    /** Detect common open-source license header start lines */
    private static final Pattern LICENSE_HEADER_START = Pattern.compile(
            "(?im)^(\\s*(/\\*+|#|//|<!--)\\s*(Copyright|License|Licensed under|SPDX-License-Identifier|Permission is hereby granted|This (file|software|program|source)|The MIT License|Apache License|GNU General Public|Mozilla Public))");

    // ── Public API ──────────────────────────────────────────────────────────────

    /**
     * Returns {@code true} if the file at {@code filePath} should be skipped entirely
     * (generated files, lock files, source maps, etc.).
     */
    public boolean isGeneratedFile(String filePath, String content) {
        String lower = filePath.toLowerCase();

        // Check exact file name match
        String fileName = filePath.contains("/")
                ? filePath.substring(filePath.lastIndexOf('/') + 1)
                : filePath;
        if (GENERATED_FILE_NAMES.contains(fileName.toLowerCase())) {
            log.debug("Skipping generated file (name match): {}", filePath);
            return true;
        }

        // Check suffix match
        for (String suffix : GENERATED_SUFFIXES) {
            if (lower.endsWith(suffix)) {
                log.debug("Skipping generated file (suffix match {}): {}", suffix, filePath);
                return true;
            }
        }

        // Check content markers in first 500 chars (fast header scan)
        if (content != null && content.length() > 0) {
            String header = content.substring(0, Math.min(500, content.length()));
            for (String marker : GENERATED_CONTENT_MARKERS) {
                if (header.contains(marker)) {
                    log.debug("Skipping generated file (content marker '{}'): {}", marker, filePath);
                    return true;
                }
            }
        }

        return false;
    }

    /**
     * Redacts secrets, PII, and sensitive patterns from {@code content} before
     * it is chunked and stored in the vector database.
     *
     * @return sanitised content with sensitive values replaced by placeholders
     */
    public String redactSensitiveData(String content, String filePath) {
        if (content == null || content.isBlank()) return content;

        String result = content;
        int redactions = 0;

        // PEM private keys (replace entire block)
        result = PEM_PRIVATE_KEY.matcher(result).replaceAll("[REDACTED_PRIVATE_KEY]");

        // Bearer tokens
        result = BEARER_TOKEN.matcher(result).replaceAll("$1[REDACTED_TOKEN]");

        // Well-known secret key prefixes
        result = GENERIC_SECRET_KEY.matcher(result).replaceAll("[REDACTED_API_KEY]");

        // .env-style assignments — keep key name, redact value only
        result = ENV_ASSIGNMENT.matcher(result).replaceAll("$1=[REDACTED]");

        // Connection strings with credentials
        result = CONNECTION_STRING.matcher(result).replaceAll("$1://[REDACTED]@");

        // Email addresses
        result = EMAIL.matcher(result).replaceAll("[REDACTED_EMAIL]");

        // Private-range IP addresses
        result = PRIVATE_IP.matcher(result).replaceAll("[REDACTED_IP]");

        if (!result.equals(content)) {
            log.debug("Redacted sensitive data in: {}", filePath);
        }

        return result;
    }

    /**
     * Strips leading license/copyright header blocks from file content.
     * Returns the content starting from the first non-comment, non-license line.
     */
    public String stripLicenseHeader(String content) {
        if (content == null || content.isBlank()) return content;

        String[] lines = content.split("\r?\n", -1);

        // Find first line that looks like a license header
        int headerStart = -1;
        for (int i = 0; i < Math.min(lines.length, 5); i++) {
            if (LICENSE_HEADER_START.matcher(lines[i]).find()) {
                headerStart = i;
                break;
            }
        }

        if (headerStart == -1) return content; // no license header detected

        // Scan forward to find end of the comment block
        int headerEnd = headerStart;
        boolean inBlockComment = lines[headerStart].contains("/*");

        for (int i = headerStart; i < Math.min(lines.length, 60); i++) {
            String line = lines[i].trim();
            if (inBlockComment) {
                if (line.contains("*/")) { headerEnd = i; break; }
            } else {
                // Single-line comment run (#, //, <!--)
                if (!line.startsWith("#") && !line.startsWith("//")
                        && !line.startsWith("<!--") && !line.startsWith("*")
                        && !line.isBlank()) {
                    headerEnd = i - 1;
                    break;
                }
                headerEnd = i;
            }
        }

        // Rebuild content without the header block
        StringBuilder sb = new StringBuilder();
        for (int i = headerEnd + 1; i < lines.length; i++) {
            sb.append(lines[i]).append("\n");
        }
        return sb.toString();
    }
}
